/** A little ad hoc script to add famous actors to the database.
 *
 * Run from the project root with `npx ts-node src/famous_actors/addFamousActorsToDB.ts`.
 *
 * Sometimes we clear the database for whatever reason and I want to be able to quickly
 * add a list of very famous actors to the database. The way we usually populate the database
 * is by fetching the "popular people" list from TMDB, and that list won't contain famous actors
 * from the past. This script is a quick way to add some of those actors to the database.
 *
 * This script reads from famousActorIdsToNames.ts, which is a file generated by another script.
 * Make sure that file is up to date before running this script.
 *
 * NOTE: This script only adds the actors, not their credits. The credits will be added when
 * we run the populateDataStore script, which happens daily.
 */

import { ActorOrCategoryData } from "src/adapters/graph/movies";
import PostgreSQLMovieDataStoreHandler from "src/adapters/graph_data_store_handlers/movies/postgreSQLMovieDataStoreHandler";
import { EntityType } from "src/ports/graph";
import { famousActorIdsToNames } from "./famousActorIdsToNames";

async function main() {
  const dataStoreHandler = new PostgreSQLMovieDataStoreHandler();

  await dataStoreHandler.init();

  const actorData: ActorOrCategoryData[] = [];
  for (const [actorId, actorName] of Object.entries(famousActorIdsToNames)) {
    actorData.push({
      id: actorId,
      name: actorName,
      entityType: EntityType.NON_CATEGORY,
    });
  }

  await dataStoreHandler.writeActorsAndCategoriesToDB(actorData);
}

if (require.main === module) {
  main();
}
