/** A little ad hoc script to add famous actors to the database.
 *
 * Run from the project root with `npx ts-node src/famous_actors/addFamousActorsToDB.ts`.
 *
 * Sometimes we clear the database for whatever reason and I want to be able to quickly
 * add a list of very famous actors to the database. The way we usually populate the database
 * is by fetching the "popular people" list from TMDB, and that list won't contain famous actors
 * from the past. This script is a quick way to add some of those actors to the database.
 *
 * This script reads from famousActorIdsToNames.ts, which is a file generated by another script.
 * Make sure that file is up to date before running this script.
 *
 * NOTE: This script only adds the actors, not their credits. The credits will be added when
 * we run the populateDataStore script, which happens daily.
 */

import DBGraphHandler from "../graph_handlers/dbGraphHandler";
import { ActorCreditGraph } from "../interfaces";
import { famousActorIdsToNames } from "./famousActorIdsToNames";

async function main() {
  const dbGraphHandler: DBGraphHandler = new DBGraphHandler();
  await dbGraphHandler.init();

  const graph: ActorCreditGraph = { actors: {}, credits: {} };

  for (const [id, name] of Object.entries(famousActorIdsToNames)) {
    graph.actors[id] = {
      id,
      name,
      connections: {},
      entityType: "actor",
    };
  }

  await dbGraphHandler.writeActorsToDB(graph);
}

if (require.main === module) {
  main();
}
