name: Build and deploy to S3

on:
  push:
    branches: [main]
    paths:
      - 'frontend/src/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run tsc
        run: npx tsc
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_TO_S3_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync dist directory to S3
        run: aws s3 sync dist s3://${{ vars.STATIC_S3_BUCKET }}
        working-directory: frontend
