name: Deploy grid-generation Lambda

on:
  push:
    branches: [main]
    paths:
      - "grid-generation/src/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy_lambda.yml
    with:
      npm-script: generate-grid-generation-lambda-zip
      lambda-function-name: GenerateGrid
      zip-file-name: grid_generation_lambda_package.zip
