name: Deploy grid-generation Lambdas

on:
  push:
    branches: [main]
    paths:
      - "grid_generation/src/**"
      - "common/src/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy_lambdas.yml
    with:
      npm-script: generate-grid-generation-lambda-zip
      lambda-function-names: GenerateGrid PopulateDataStore
      zip-file-name: grid_generation_lambda_package.zip
