name: Deploy Lambdas

on:
  workflow_call:
    inputs:
      npm-script:
        description: "The npm script to run"
        required: true
        type: string
      lambda-function-names:
        description: "A space-separated list of names of the Lambda functions to update"
        required: true
        type: string
      zip-file-name:
        description: "The name of the zip file to upload to Lambda"
        required: true
        type: string

jobs:
  build-zip-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install jq
        run: sudo apt-get install jq

      - name: Build and zip
        run: npm run ${{ inputs['npm-script'] }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_TO_S3_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}

      # Note: The Lambda function names are passed as a string with space-separated values
      - name: Deploy Lambda function(s)
        run: |
          IFS=' ' read -r -a lambda_name_array <<< "${{ inputs['lambda-function-names'] }}"
          for function_name in "${lambda_name_array[@]}"; do
            aws lambda update-function-code --function-name "$function_name" --zip-file fileb://${{ inputs['zip-file-name'] }}
          done
