name: Deploy API Lambda

on:
  push:
    branches: [main]
    paths:
      - "api/src/**"
      - "common/src/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy_lambda.yml
    with:
      npm-script: generate-api-lambda-zip
      lambda-function-name: SearchTMDBAPI
      zip-file-name: api_lambda_package.zip
