name: Build and deploy static website to S3

on:
  push:
    branches: [main]
    paths:
      - "frontend/src/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Required for running vite in the next step
      # The node_modules created during installation of dependencies
      # isn't in the PATH without this step
      - name: Update PATH
        run: echo "$GITHUB_WORKSPACE/frontend_dist/node_modules/.bin" >> $GITHUB_PATH

      - name: Install dependencies and build
        run: npm run generate-frontend-dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_TO_S3_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync dist directory to S3
        run: aws s3 sync ./frontend_dist/frontend/dist s3://${{ vars.STATIC_S3_BUCKET }}
