name: Deploy Lambda

on:
  workflow_call:
    inputs:
      npm-script:
        description: 'The npm script to run'
        required: true
        type: string
      lambda-function-name:
        description: 'The name of the Lambda function to update'
        required: true
        type: string
      zip-file-name:
        description: 'The name of the zip file to upload to Lambda'
        required: true
        type: string

jobs:
  build-zip-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install jq
        run: sudo apt-get install jq

      - name: Build and zip
        run: npm run ${{ inputs['npm-script'] }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_TO_S3_ROLE }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy Lambda function
        run: aws lambda update-function-code --function-name ${{ inputs['lambda-function-name'] }} --zip-file fileb://${{ inputs['zip-file-name'] }}
